// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Natsume.Persistence;

#nullable disable

namespace Natsume.Migrations
{
    [DbContext(typeof(NatsumeDbContext))]
    [Migration("20250726142906_MeetingsAndRefactorContacts")]
    partial class MeetingsAndRefactorContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Natsume.Database.Entities.NatsumeContact", b =>
                {
                    b.Property<ulong>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentFavor")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordNickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFriend")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastInteraction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MetOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimeFriendship")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFavorExpended")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("TotalInteractions")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Natsume.Database.Entities.NatsumeMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRandomMeeting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Natsume.Database.Entities.NatsumeReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemindMeAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReminderText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
