// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Natsume.Database;

#nullable disable

namespace Natsume.Migrations
{
    [DbContext(typeof(NatsumeDbContext))]
    partial class NatsumeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Natsume.Database.Entities.NatsumeContact", b =>
                {
                    b.Property<ulong>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActivityFriendship")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvailableFavor")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FriendsSince")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFriend")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMessageOn")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MessageFriendship")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimeFriendship")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFavorExpended")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordId");

                    b.ToTable("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
